### ISSUE TITLE
Request for Yesod + Keycloak web app simple authentication example

### ISSUE THREAD

**Issue by ciukstar** [cdupont/keycloak-hs#3]
Hi! 
May I ask you for an example of a simple Yesod web application that authenticates users with Keycloak? Or at least is it possible to authenticate users with Keycloak by redirecting to the Keycloak input form? 
Thanks.

**Comment by cdupont** [comment]
Hi @ciukstar ,
very good question, I can add an example with Yesod. Please allow some days...

**Comment by ciukstar** [comment]
> Hi @ciukstar , very good question, I can add an example with Yesod. Please allow some days...

Thanks

**Comment by cdupont** [comment]
In the meantime you can look this doc: https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter

It shows the code to put in your Javascript app. This code will redirect the user to the Keycloak input form for login in users.
For my own app, the page generated by Keycloak looks like that:

![image](https://user-images.githubusercontent.com/484033/136369602-4d84e350-2409-4a19-8d37-19e6d8f2cca7.png)

My front-end is witten in Javascript. My back-end is in Haskell.
So the front-end redirects to the login page, and obtains a token. The token is then used by the front-end for all requests to the back-end.
This library is used by the back-end to verify the token and claims.

**Comment by ciukstar** [comment]
> In the meantime you can look this doc: https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter
> 
> It shows the code to put in your Javascript app. This code will redirect the user to the Keycloak input form for login in users. For my own app, the page generated by Keycloak looks like that:
> 
> ![image](https://user-images.githubusercontent.com/484033/136369602-4d84e350-2409-4a19-8d37-19e6d8f2cca7.png)
> 
> My front-end is witten in Javascript. My back-end is in Haskell. So the front-end redirects to the login page, and obtains a token. The token is then used by the front-end for all requests to the back-end. This library is used by the back-end to verify the token and claims.

Thanks. 
I do use Keycloak JavaScript adapter for my Angular + Keycloak web apps. Now I am writing/learning a new Yesod web application and I am wondering if there is a more "correct" way of doing it. The Yesod way?! The keycloak-hs way?! The Yesod + keycloak-hs way?!

**Comment by cdupont** [comment]
I don't know Yesod so I'll have to look it up and come back to you...

**Comment by ciukstar** [comment]
It worked for me by creating a plugin as described in section "Local Providers" on https://hackage.haskell.org/package/yesod-auth-oauth2

Thanks.

**Comment by cdupont** [comment]
That is great! I'm curious to know how that went. Maybe you have code on github?
